### ISSUE TITLE
CrashDumps...

### ISSUE THREAD

**Issue by FIRERO** [iTXTech/Genisys#1161]
Hi, and now are two crashdups...
I use 6 GB RAM!!!! And in cofings, I wrote 6144 mb!!

```

Genisys Crash Dump Wed Jun 15 01:32:57 CDT 2016

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 12288 bytes)
File: /src/pocketmine/utils/Config
Line: 132
Type: E_ERROR

Code:
[123] 				$extension = explode(".", basename($this->file));
[124] 				$extension = strtolower(trim(array_pop($extension)));
[125] 				if(isset(Config::$formats[$extension])){
[126] 					$this->type = Config::$formats[$extension];
[127] 				}else{
[128] 					$this->correct = false;
[129] 				}
[130] 			}
[131] 			if($this->correct === true){
[132] 				$content = file_get_contents($this->file);
[133] 				switch($this->type){
[134] 					case Config::PROPERTIES:
[135] 					case Config::CNF:
[136] 						$this->parseProperties($content);
[137] 						break;
[138] 					case Config::JSON:
[139] 						$this->config = json_decode($content, true);
[140] 						break;
[141] 					case Config::YAML:
[142] 						$content = self::fixYAMLIndexes($content);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.1dev #416 [Protocol 70; API 2.0.0]
uname -a: Linux gfc-pe.ru 3.19.0-51-generic #58~14.04.1-Ubuntu SMP Fri Feb 26 22:02:58 UTC 2016 x86_64
PHP version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
加载的插件:
SWorldEditor Beta_1.5 by Sergey_Dertan for API(s) 1.8.0
PopupTimer 1 by FIRERO for API(s) 2.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
OwnShop 1.0.0 by FIRERO for API(s) 2.0.0
```

```

Genisys Crash Dump Wed Jun 15 00:55:09 CDT 2016

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes)
File: /src/pocketmine/utils/Config
Line: 143
Type: E_ERROR

Code:
[134] 					case Config::PROPERTIES:
[135] 					case Config::CNF:
[136] 						$this->parseProperties($content);
[137] 						break;
[138] 					case Config::JSON:
[139] 						$this->config = json_decode($content, true);
[140] 						break;
[141] 					case Config::YAML:
[142] 						$content = self::fixYAMLIndexes($content);
[143] 						$this->config = yaml_parse($content);
[144] 						break;
[145] 					case Config::SERIALIZED:
[146] 						$this->config = unserialize($content);
[147] 						break;
[148] 					case Config::ENUM:
[149] 						$this->parseList($content);
[150] 						break;
[151] 					default:
[152] 						$this->correct = false;
[153] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.1dev #416 [Protocol 70; API 2.0.0]
uname -a: Linux gfc-pe.ru 3.19.0-51-generic #58~14.04.1-Ubuntu SMP Fri Feb 26 22:02:58 UTC 2016 x86_64
PHP version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
加载的插件:
SWorldEditor Beta_1.5 by Sergey_Dertan for API(s) 1.8.0
PopupTimer 1 by FIRERO for API(s) 2.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
OwnShop 1.0.0 by FIRERO for API(s) 2.0.0
```

genisys.yml:
```
#Genisys Advanced Configuration File

#Version of this file
config:
 version: 15

level:
 #Set if turn on the weather system
 weather: false
 #Weather switch interval
 weather-change-time: 6000
 #Weather Duration，default as 1 min
 weather-last-time: 1200
 #Random lightning interval，default as 10s
 lightning-time: 200
 
player:
 #the switch of hunger system
 hunger: true
 #Minimum health when someone is attacking by being hungry
 hunger-health: 15
 #Hunger Time-Counter, Default: 80=4sec
 hunger-timer: 5000
 #Choose if turn on the experience system
 experience: true
 #Choose if keep inventory when a player died
 keep-inventory: false
 #The space of inventory
 inventory-num: 40
 #Clear the inventory automatically when change the gamemode into creative
 auto-clear-inventory : false
 #TODO: Choose if keep experience when a player died
 keep-experience: false
 #Choose how to remind player when a player join
 #0 = Message, 1 = Tip, 2 = Popup
 player-msg-type: 2
 login-msg: "§3@player зашёл на сервер!"
 logout-msg: "§3@player покинул сервер."

nether:
 #Choose if the nether's allowed,the level of nether will generate automatically
 allow-nether: true
 #The name of nether's level
 level-name: "nether"
 
server:
 #Pregenerate the experience data，0=disabled
 experience-cache: 65535
 #Choose if spawning iron golem is allowed
 allow-iron-golem: false
 #Choose if spawning snow golem is allowed
 allow-snow-golem: false
 #Choose if anvil and enchanttable are allowed
 allow-anvilandenchanttable: true
 #Choose if disable server.log
 disable-log: false
 #Choose if enable auto anti fly
 anti-fly: true

redstone:
 #Choose if redstone system is allowed
 enable: false
 #Choose if allow fake low frequancy pulse
 allow-fake-low-frequency-pulse: false
 #Set the frequency of pulse, Default: 1s
 pulse-frequency: 1

synapse:
 #If you want to use Synapse API or connect to a synapse server, enable this
 enabled: true
 server-ip: 127.0.0.1
 server-port: 10305
 is-main-server: true
 server-password: 32bitlongkey
 description: "A Synapse client"
 
dserver:
 #The count of all multi-server unified
 enable: false
 #Query update automatically
 query-auto-update: true
 #Query update periodical
 query-tick-update: true
 #The max players' number of Motd
 motd-max-players: 0
 #The max players' number of query，0=Default
 query-max-players: 0
 #Show the number of all players on motd
 motd-all-players: false
 #Show the number of all players on Query
 query-all-players: false
 #Show the number of online players on motd
 motd-players: false
 #Show the number of online players on Query
 query-players: false
 #Update Frequency ,20=1s
 time: 20
 #Auto-retry times when failed
 retry-times: 3
 #the server list，Separate by ';'，e.g. a.cn:19132;b.cn:19132
 server-list: ""
 
ai:
 #AI switch
 enable: false
 #Zombie'AI，0=disabled，1=AI 1.0ver，2=new AI(Faultiness)
 zombie: 0
 #PigZombie's AI
 pigzombie: false
 #the AI of cow and mushroom cow
 cow: false
 #Chicken's AI
 chicken: false
 #Sheep's AI
 sheep: false
 #Pigs' AI
 pig: false
 #Skeleton's AI
 skeleton: false
 #Creeper's AI
 creeper: false
 #Iron golem's AI
 iron-golem: false
 #Snow golem's AI
 snow-golem: false
 #Destory blocks if creeper exploded
 creeper-explode-destroy-block: false
 #Choose if allow mob auto generate
 mobgenerate: false
```

pocketmine.yml:
```
---
settings:
  language: rus
  force-language: true
  shutdown-message: Сервер отключился. Перезайдите.
  query-plugins: true
  deprecated-verbose: true
  enable-profiling: true
  profile-report-trigger: 15
  async-workers: 6
memory:
  global-limit: 6144
  main-limit: 2048
  check-rate: 20
  continuous-trigger: true
  continuous-trigger-rate: 30
  garbage-collection:
    period: 18000
    collect-async-worker: true
    low-memory-trigger: true
  max-chunks:
    trigger-limit: 192
    trigger-chunk-collect: true
    low-memory-trigger: true
  world-caches:
    disable-chunk-cache: true
    low-memory-trigger: false
network:
  batch-threshold: 256
  compression-level: 5
  async-compression: true
  upnp-forwarding: false
debug:
  level: 1
  commands: true
level-settings:
  default-format: mcregion
  convert-format: true
  auto-tick-rate: true
  auto-tick-rate-limit: 5
  base-tick-rate: 2
  always-tick-players: false
chunk-sending:
  per-tick: 50
  max-chunks: 192
  spawn-threshold: 56
  cache-chunks: true
chunk-ticking:
  per-tick: 2
  tick-radius: 6
  light-updates: false
  clear-tick-list: true
chunk-generation:
  queue-size: 4
  population-queue-size: 8
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  autosave: 6000
  cache-cleanup: 900
spawn-limits:
  monsters: 70
  animals: 15
  water-animals: 5
  ambient: 15
auto-report:
  enabled: true
  send-code: true
  send-settings: true
  send-phpinfo: false
  host: crash.pocketmine.net
anonymous-statistics:
  enabled: true
  host: stats.pocketmine.net
auto-updater:
  enabled: false
  on-update:
    warn-console: false
    warn-ops: false
  preferred-channel: beta
  suggest-channels: false
  host: www.pocketmine.net
aliases:
  savestop:
  - save-all
  - stop
worlds: ~
settings.language: eng
...

```
