### ISSUE TITLE
Mob Auto spawn in Server

### ISSUE THREAD

**Issue by K099** [iTXTech/Genisys#1427]
#### Issue description
Mob Auto spawn in world Periodically

#### OS and versions
* Genisys: Last source
* PHP: 7
* OS (server): Ubuntu
* Game version: 0.15.2

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
genisys.yml

 
ai:
 #AI switch
 enable: false
 #Zombie'AI，0=disabled，1=AI 1.0ver，2=new AI(Faultiness)
 zombie: 1
 #PigZombie's AI
 pigzombie: true
 #the AI of cow and mushroom cow
 cow: true
 #Chicken's AI
 chicken: true
 #Sheep's AI
 sheep: true
 #Pigs' AI
 pig: true
 #Skeleton's AI
 skeleton: true
 #Creeper's AI
 creeper: true
 #Iron golem's AI
 iron-golem: true
 #Snow golem's AI
 snow-golem: true
 #Destory blocks if creeper exploded
 creeper-explode-destroy-block: false
 #Choose if allow mob auto generate
 mobgenerate: false
```
![screenshot_2016-07-10-23-52-48](https://cloud.githubusercontent.com/assets/19483521/16715201/059b3538-4704-11e6-9309-7b4c8ab552a2.png)
![screenshot_2016-07-10-23-53-05](https://cloud.githubusercontent.com/assets/19483521/16715203/059d134e-4704-11e6-8333-1b5f751e25dc.png)
![screenshot_2016-07-11-00-58-45](https://cloud.githubusercontent.com/assets/19483521/16715205/05a02ce6-4704-11e6-9ed3-65dd1df419a1.png)
![screenshot_2016-07-10-13-53-46](https://cloud.githubusercontent.com/assets/19483521/16715202/059bc0ca-4704-11e6-9a9a-433b3b152946.png)
![screenshot_2016-07-10-13-53-50](https://cloud.githubusercontent.com/assets/19483521/16715204/059e36b6-4704-11e6-9855-e8edd86fbc6c.png)
![screenshot_2016-07-10-19-27-29](https://cloud.githubusercontent.com/assets/19483521/16715206/05a2f5fc-4704-11e6-9f0a-864e1146796f.png)
