### ISSUE TITLE
Level doesn't load on startup

### ISSUE THREAD

**Issue by Gianluxx** [iTXTech/Genisys#2207]
#### Issue description

Levels that are in pocketmine.yml config file don't get Loaded when the server starts.

#### Steps to reproduce the issue
Add a world name in the file like this:

worlds:
 survival: []
 Island: []

#### OS and versions
* Genisys: 6e91f61
* PHP: 7
* Server OS: Linux 
* Game version: 0.16

**Comment by iPocket** [comment]
Missing - on the start of worldnames.
it should be like this:
```
worlds:
- survival: []
- Island: []
```

**Comment by Gianluxx** [comment]
not working

**Comment by dktapps** [comment]
Your format is incorrect. Use the example.

**Comment by dktapps** [comment]
```
worlds:
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 world:
  seed: 404
  generator: FLAT:2;7,120x1,3x3,2;1;decoration(treecount=80 grasscount=45)
```
