### ISSUE TITLE
Request: add Subban

### ISSUE THREAD

**Issue by NML32** [iTXTech/Genisys#968]
Could you add Subnet ban?  It would be a nice addition like you did for cidban.

Thanks....

**Comment by Muqsit** [comment]
It's better if you have a separate plugin for that or just use shell script to modify Genisys.

**Comment by NML32** [comment]
I'm using a plugin to sub ban but I found out it doesn't have perms and users have started banning IPs.

**Comment by Leo3418** [comment]
Are you mentioning [SubnetBan](http://forums.pocketmine.net/plugins/subnet-ban.548/)?
Actually you can edit the plugin by yourself. Simply extract the plugin, then edit plugin.yml like this:
```
 subban:
  description: "Bans the players subnet"
  usage: "/subban <add|remove|list|reload> [IP|player]"
  permission: op
```
